var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/services/road-service/page.js")
R.c("server/chunks/ssr/_0nf83qb._.js")
R.c("server/chunks/ssr/_0pm-ota._.js")
R.c("server/chunks/ssr/components_ui_button_tsx_0jslpqj._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0v8r5qp.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g1k.x9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0na1wqe._.js")
R.c("server/chunks/ssr/[root-of-the-server]__00cgtdw._.js")
R.c("server/chunks/ssr/[root-of-the-server]__10v850o._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09fw.ri._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_services_road-service_page_actions_0fvanop.js")
R.m(97521)
module.exports=R.m(97521).exports
